### ISSUE TITLE
.ical a nejistá pyva

### ISSUE THREAD

**Issue by honzajavorek** [pyvec/pyvo.cz#106]
Je nějaký způsob v rámci .ical, jak systematicky rozlišit nejistá Pyva od jistých? Že bych ta nejistá na https://python.cz/akce/ udělal třeba šedou barvou a tak. Ale nechce se mi dělat

```python
>>> import re
>>> re.match(r'\([^\)]+ Pyvo\?\)', '(Brněnské Pyvo?)')
```

to mi přijde takový hloupý. Nebo je to možná good enough?

**Comment by encukou** [comment]
Nevim, ale jestli neni, muzes mit dva iCaly.

**Comment by encukou** [comment]
Až se spraví #103, normální události budou mít URL, ale ty nenaplánované ne. Bude to stačit?

**Comment by honzajavorek** [comment]
To se obávám, že stačit nebude, protože RSS reader na python.cz by se měl k jednotlivým feedům chovat agnosticky - bere je z YAML souboru jeden po druhém a bez speciální péče je splácne dohromady a pak vyhodnocuje jednotlivé eventy. Tzn. pokud mám Google Calendar ze kterého nepřijde URL k události, považoval bych ho za neplánovaný event, a to není správně.

**Comment by encukou** [comment]
Jaký by byl ideální způsob, jak dát tuhle informaci vědět? Ten regex mi přijde horší než special-case na Pyva + kouknout na URL.

**Comment by honzajavorek** [comment]
Ja myalel jestli iCal samotný nemá podporu pro nějaká metadata, kam by se
to dalo dat a Python.cz čtečka by to tam mohla vyčíst. Možná by stačilo
přidat nestandardní “tag” nebo jak se tomu říká? Google Calendar tam má
taky spoustu svých věcí a předpokládám, že když to čtečka nezná, proste tu
sekci přeskočí.

**Comment by encukou** [comment]
Existují kategorie!  viz #110

**Comment by honzajavorek** [comment]
Hehe, když jsem si vypsal kategorie toho, co tam máme, očividně je meetup.com nastavuje:

```
{'Computer programming', 'Open Source', 'Python', 'Web Technology', 'Technology Professionals', 'Women in Technology'}
{'Open Source', 'Machine Learning', 'Data Visualization', 'Big Data', 'Software Development', 'Business Intelligence', 'New Technology', 'Community Building', 'Data Analytics', 'Computer programming', 'Technology', 'Predictive Analytics'}
{'tentative-date'}
```
