### ISSUE TITLE
Broken links to NePyvo

### ISSUE THREAD

**Issue by honzajavorek** [pyvec/pyvo.cz#129]
Přišlo na info@pyvec.org od Jirky Guňky:

> Když z výsledků vyhledávání Google "Nepyvo" prokliknu na web pyvo.cz dostanu 404. Jde o tyto adresy
> - https://pyvo.cz/en/nepyvo/
> - https://pyvo.cz/nepyvo/all/

**Comment by kvbik** [comment]
https://github.com/pyvec/pyvo-data/pull/303

**Comment by honzajavorek** [comment]
Njn, tak potom by bylo dobry udelat nakej redirect, at lidi z googlu nekonci na 404.

**Comment by kvbik** [comment]
Souhlasim, jenom dokumentuju, protoze mi ten problem znel povedome.
