### ISSUE TITLE
Odkaz v popisu události

### ISSUE THREAD

**Issue by honzajavorek** [pyvec/pyvo.cz#141]
Bylo by fajn, kdyby odkaz byl opravdu odkaz:

<img width="832" alt="image" src="https://user-images.githubusercontent.com/283441/100377633-df11e000-3011-11eb-8fb0-093b231d0747.png">

Je to bug, feature, nebo musí autor popisu události udělat něco speciálního, aby odkaz byl odkaz?

**Comment by encukou** [comment]
Je to Markdown, takže odkaz se dělá přes `[popis](url)`.
Poslal jsem #371.

**Comment by honzajavorek** [comment]
Hmm, takže to nedělá autodetekci URL, když je přímo v textu? 🤔 Zajímavé. Díky.
