### ISSUE TITLE
Počítat s tím, že srazy nemusí být jen Pyvo, ale jsou někdy spojené

### ISSUE THREAD

**Issue by honzajavorek** [pyvec/pyvo.cz#15]
- Rubači
- BRUG
- CzechiPub
- DevOps Pyvo
- Docker
- ...

**Comment by encukou** [comment]
Každý sraz má individuální název, kde může být třeba [Brněnské Pyvo + BRUG + CzechiPub](https://pyvo.cz/brno-pyvo/2015-02/).
