### ISSUE TITLE
Přidat kamarády

### ISSUE THREAD

**Issue by honzajavorek** [pyvec/pyvo.cz#18]
* [ ] BRUG (existuje ještě?), Rubači, pražské Ruby srazy
* [ ] Symfonisti? @TomasVotruba jste kamarádi, žejo? :-D
* [x] Python srazy na Slovensku (pycon.sk)
* [ ] CzechiPub?

**Comment by TomasVotruba** [comment]
@honzajavorek Jasně, však jsme skoro bráchové :) občas něco retweetnu. Rád bych propagoval i nějaký vzájemný přesah, ale zatím o ničem nevím.

**Comment by honzajavorek** [comment]
@TomasVotruba OK! Vzájemný přesah... to přijde časem, třeba někoho něco napadne :)

**Comment by encukou** [comment]
BRUG vypadá mrtvě :cry: Nebo jen snížili frekvenci srazů?
https://plus.google.com/u/0/communities/103416598353551503738
https://twitter.com/brugcz
@iNecas, @pitr-ch, žijete?

**Comment by encukou** [comment]
Rubaci: https://www.facebook.com/rubaci
Pražské Ruby srazy - http://www.meetup.com/Praguerb/
Symfonisti - http://www.symfony.cz/
Slovenské srazy (pycon.sk): https://pycon.sk/sk/meetup.html
CzechiPub - ?

**Comment by honzajavorek** [comment]
Rubaci maji pokud vim i normalni web: http://rubaci.cz/

**Comment by honzajavorek** [comment]
A prazske Ruby srazy jsou tady: https://www.facebook.com/groups/117356151611087/events/, ale mozna je to to samy jako na tom meetup.com. Jestli maji nejaky web nevim. Jak to je, @jana4u?

**Comment by encukou** [comment]
@danieldimitrov, mají Rubači nějakou stránku, kam by se dalo odkázat? FB i rubaci.cz vypadají opuštěně.

**Comment by danieldimitrov** [comment]
@encukou Myslím, že všechno je mrtvé a nikdo nic pravidelně nesleduje. Na FB je několik aktivních ruby/rails skupin. To je asi tak jediné místo, které mě napadá.

**Comment by iNecas** [comment]
Ahoj, "mrtvé" nemá z nějakého důvodu úplně pozitivní podtón. Nazval bych to
spíš zimní spánek :)

-- Ivan

2016-02-27 17:41 GMT+01:00 Petr Viktorin <notifications@github.com>:

**Comment by danieldimitrov** [comment]
Pozitivní podtón to nemá, ale je to tak. Pokud to je zimní spánek tak trvá už několik let. Nevím o žádném místě, které by aktivně sledovala komunita v ČR plošně (výjma těch několika FB skupin). Pokud nějaké znáš, tak sem s ním, budu jen rád.

**Comment by jana4u** [comment]
@honzajavorek Pražské ruby srazy spíš na: http://srazy.info/prvni-streda-ruby-on-rails
Případně na Facebooku: https://www.facebook.com/groups/117356151611087/ a Google+: https://plus.google.com/107018734141903637772
Ke srazu na Meetup.com nemám přístup a tedy dost pravděpodobně tam ne každý sraz bude.
