### ISSUE TITLE
Dodat kontaktní informace

### ISSUE THREAD

**Issue by honzajavorek** [pyvec/pyvo.cz#19]
Ostrava a Praha nemají mail / telefon na organizátory. Možná bychom mohli přidat i odkaz na místo, kde se domlouvají organizátoři? https://groups.google.com/forum/#!forum/brno-pyvo apod.?

**Comment by kvbik** [comment]
uf.. misto kde se prazaci domlouvaji asi neni.. takze neco takoveho by se melo zalozit. zatim bych tam klidne dal telefon a mail na alese, jirku, jakuba.

jakub.vysoky@gmail.com +420605852377

**Comment by lspdv** [comment]
ale máte to hlavně napsaný na úvodní stránce, že to je na odkazech měst, ale není.

tak šup šup, dělám anketu zpětnovazbní a chtěla bych to tam napsat. @frenzymadness, @kvbik

**Comment by lspdv** [comment]
#31

**Comment by lspdv** [comment]
#32

**Comment by frenzymadness** [comment]
Omlouvám se @lspdv ale nevšiml jsem si tvého PR a udělal jsem vlastní, kde jsem dal i Google group a Laca: https://github.com/pyvec/pyvo.cz/pull/33

Prosím někoho polovaného o merge.

**Comment by lspdv** [comment]
To je naprosto v pohode, ja jsem rada, ze moje donucovaci taktika zafungovala :smile: :trollface:

**Comment by lspdv** [comment]
V #33 je ale asi nejakej problem, rikal strejda Trávis, hele to necham zkusenejsim

**Comment by encukou** [comment]
Už jsou tam! Díky přispěvatelům :)

p.s. od teď jsou ty informace v pyvo-data, [např.  tady](https://github.com/pyvec/pyvo-data/blob/master/series/ostrava-pyvo/series.yaml#L11).
