### ISSUE TITLE
Handle all existing subdomains

### ISSUE THREAD

**Issue by honzajavorek** [pyvec/pyvo.cz#2]
- brno, ostrava, praha seems to work as intended
- brnenske, ostravske, prazske -> fails
- prague -> fails

**Comment by encukou** [comment]
Wow. This is the first time I hear about those subdomains.

**Comment by encukou** [comment]
Deployed; it should work now

**Comment by honzajavorek** [comment]
They were already set in the domain settings, so I kept them.
