### ISSUE TITLE
pyvo.cz/zaloz → pyvec/meetup-guide

### ISSUE THREAD

**Issue by honzajavorek** [pyvec/pyvo.cz#20]
http://pyvec-guide.readthedocs.org/guides/meetup.html

**Comment by kvbik** [comment]
i am not 100% sure, what we should do here, redirect?

**Comment by honzajavorek** [comment]
Link. I thought it's not there yet.

**Comment by honzajavorek** [comment]
Several places link to pyvo.cz/zaloz, but they could link directly to RTD
