### ISSUE TITLE
iCal pro každé město / sraz

### ISSUE THREAD

**Issue by honzajavorek** [pyvec/pyvo.cz#21]

**Comment by kvbik** [comment]
easy - lanyrd does that ;) there is a link in the series!

http://lanyrd.com/series/praha-pyvo/praha-pyvo.ics

**Comment by kvbik** [comment]
vsechny (musi se plnit ten guide):

* http://lanyrd.com/guides/pyvo/pyvo.ics

individualne:

* http://lanyrd.com/series/praha-pyvo/praha-pyvo.ics
* http://lanyrd.com/series/brno-pyvo/brno-pyvo.ics
* http://lanyrd.com/series/ostrava-pyvo/ostrava-pyvo.ics

**Comment by kvbik** [comment]
kam s tim dal @honzajavorek ^^ ?

**Comment by honzajavorek** [comment]
wooohooo, ja vlastne nevim, pyvo.cz ma v maliku @encukou

**Comment by encukou** [comment]
Kalendáře pro každé Pyvo jsou [online](https://pyvo.cz/api/series/brno-pyvo.ics) a odkázané z každé [stránky města](https://pyvo.cz/brno-pyvo).
