### ISSUE TITLE
Ujasnit, že na sraz není potřeba se registrovat

### ISSUE THREAD

**Issue by honzajavorek** [pyvec/pyvo.cz#22]
Dostal jsem dotaz:

> Na sraz Python specialistů je nutné se registrovat?

Bylo by dobré, aby to bylo nějak zřejmé už z webu. Nevím přesně, co pro to udělat.

**Comment by lspdv** [comment]
Nepsat to tam? :trollface:

**Comment by lspdv** [comment]
Hele ale třeba Lumír tam potvrzovat úřast chce.

**Comment by honzajavorek** [comment]
hmm, takze napsat to tam, ale ke kazdemu mestu zvlast :)

**Comment by lspdv** [comment]
to je ale trochu nahoubeles, tam podle me skoro nikdo nedojde, kdo hleda jen info o srazu

**Comment by encukou** [comment]
Tohle si každé město může napsat do popisku.
