### ISSUE TITLE
prague meetup date not updated

### ISSUE THREAD

**Issue by kvbik** [pyvec/pyvo.cz#24]
any idea, why the date on pyvo.cz is not updated, when there is the new meetup on lanyrd [1] for couple days already?

![image](https://cloud.githubusercontent.com/assets/45091/14085049/88157eb2-f4d2-11e5-86b4-c433fc75990b.png)

[1] http://lanyrd.com/2016/praha-pyvo-april/

**Comment by encukou** [comment]
It seems no one was around to do the update during the holidays. And more automation is still on the TODO list.

**Comment by kvbik** [comment]
is there an issue for the this todo?

**Comment by encukou** [comment]
Can't find any. I've talked about the direction I'm taking pyvo.cz in at meetups, but I guess I should write about it more.

**Comment by honzajavorek** [comment]
Some background is here: http://pyvec-guide.readthedocs.org/guides/meetup.html#materialy-z-prednasek

**Comment by kvbik** [comment]
i will check it out, thx!
