### ISSUE TITLE
Přesměrování www

### ISSUE THREAD

**Issue by honzajavorek** [pyvec/pyvo.cz#25]
Sice http://www.pyvo.cz funguje, ale http://www.pyvo.cz/brno už ne. Redirect by tedy měl být sofistikovanější. Platí bohužel i pro https://github.com/pyvec/python.cz/pull/104.

**Comment by frenzymadness** [comment]
Kde je ten web hostován? Hádám, že nstavení rediectu bude (alespoň pro mě) daleko snazší přímo na staně webového serveru.

**Comment by honzajavorek** [comment]
Je to na Roští.cz a je tam NGINX, ale kdyby to šlo v kódu, bylo by to přenositelnější.

**Comment by encukou** [comment]
Už to funguje, díky @Dundee!

**Comment by honzajavorek** [comment]
:
