### ISSUE TITLE
Design, který bude víc zapadat do python.cz, blog.python.cz, ... :-P

### ISSUE THREAD

**Issue by honzajavorek** [pyvec/pyvo.cz#29]

**Comment by encukou** [comment]
Nebo změnit ty ostatní? :P

**Comment by encukou** [comment]
Já nejsem příznivcem toho, abychom pro všechny stránky používali jednotný vizuální styl. Nejsme korporace s branding departmentem. To, že pycon.cz, pyvo.cz a python.cz vypadají jinak, podle mě ničemu nevadí. A konkrétně na skoro čistý Bootstrap se mi moc přecházet taky nechce.

Můžeme o tom podiskutovat, jestli chceš – stačí to tu znovu otevřít.

**Comment by honzajavorek** [comment]
Mě se současný design moc nelíbí, ale nemám energii momentálně tenhle
(očividně pouze svůj) problém řešit. Nechávám zavřené.

2016-10-16 17:31 GMT+02:00 Petr Viktorin <notifications@github.com>:
