### ISSUE TITLE
Na iOS zobrazuje desktop verzi a seká se

### ISSUE THREAD

**Issue by beny** [pyvec/pyvo.cz#3]
Ač se na webu zdá, že je web responzivní, na mobilu (iOS) tomu tak není. 

![screen shot 2015-12-14 at 12 19 47](https://cloud.githubusercontent.com/assets/327315/11779728/588eeb00-a25d-11e5-8cdb-228e63d27e5b.png)

![img_0226](https://cloud.githubusercontent.com/assets/327315/11779727/586ddeb0-a25d-11e5-9f03-ef9030e79f5c.PNG)

A dokonce když otočím zařízení, tak se celý prohlížec seká i na nejvýkonějším iPhone, což sem na žádné jiné stránce ještě neviděl.

**Comment by encukou** [comment]
Hmm, iOS má problém s Bootstrapem a trochou CSSka? To je trochu smutné :(
Já bohužel nemám způsob jak tohle odladit, je tu jěkdo s iPhonem kdo by se mohl kouknout který kus CSSka tohle dělá?

**Comment by martinbilek** [comment]
Jestli se jedná o boostrap, tak v hlavičce stránky chybí nějaké zásadní nastavení, viz jakýkoliv example z bootstrapu (https://github.com/twbs/bootstrap/blob/master/docs/examples/starter-template/index.html) - stačí zkopírovat. Např.:

<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <meta name="description" content="">
        <meta name="author" content="">
        .....
        .....
        
        
    </head>
.....

**Comment by tricoder42** [comment]
Smutné je používát knihovnu, nepřečíst si dokumentaci (http://getbootstrap.com/css/#overview-mobile) a pak smutnit nad špatnou podporou ze strany výrobců… Na Androidu ti to jede?

V hlavičce chybí meta tag:

```html
<meta name="viewport" content="width=device-width, initial-scale=1">
```

**Comment by beny** [comment]
Jj to bude ten problém, po přidání toho meta tagu vypadá web už OK i na iOS:

![simulator screen shot 14 12 2015 14 01 41](https://cloud.githubusercontent.com/assets/327315/11781601/48ba1804-a26b-11e5-80b4-920575a35cd6.png)

**Comment by encukou** [comment]
Aha! Tady se ukazuje že jsem amatér. Díky!

**Comment by honzajavorek** [comment]
Díky moc! Myslím že vyřešeno díky @tricoder42 v #4. A buďte mi na @encukou hodní, on je sice super mistr Yoda v Pythonu, ale webík je to jeho možná i první :-)
