### ISSUE TITLE
Zrušit odkaz na zpětnovazebník

### ISSUE THREAD

**Issue by encukou** [pyvec/pyvo.cz#41]
Kdy to dáme dolů?

**Comment by honzajavorek** [comment]
Nejpozději za měsíc, řekl bych. Ale uvidíme, jaký to má vliv na počet odpovědí - pokud se to nebude hýbat, můžeme to stáhnout i dřív.

**Comment by Formulka** [comment]
odstraním

**Comment by torsava** [comment]
Tehle issue se muze zavrit.
