### ISSUE TITLE
Přidat pycon.sk do kamarádů

### ISSUE THREAD

**Issue by honzajavorek** [pyvec/pyvo.cz#43]
Na českou i anglickou šablonu.

**Comment by encukou** [comment]
Co k nim napsat?

* [pycon.sk](http://pycon.sk) – Slovenská konference and srazy
* [pycon.sk](http://pycon.sk) – Slovak conference and meetups

**Comment by honzajavorek** [comment]
Já bych v té anglické verzi možná napsal Slovak Python User Group. Česká verze mi přijde ok.

**Comment by hroncok** [comment]
@encukou to **and** je tam schválně? Dnes jsem si toho náhodou všiml.

**Comment by encukou** [comment]
Jo, má to zahrnovat i SPy o.z. – https://spy.pycon.sk/sk/#events

**Comment by hroncok** [comment]
Myslel jsem and v české variantě.

**Comment by hroncok** [comment]
Díky. Nevěděl jsem, jestli to není nějaký vtip nebo Easter egg.

**Comment by encukou** [comment]
Jenom jsem slepej. Díky za report!
