### ISSUE TITLE
Export pro kalendárium by měl obsahovat i tušená Pyva

### ISSUE THREAD

**Issue by honzajavorek** [pyvec/pyvo.cz#47]
Kluci z Prahe občas zakládají ty pyva dost pozdě a když se nepodívám přímo na pyvo.cz do vykresleného kalendáře, stejně se nedovím včas, kdy má být, a musím si pamatovat, kolikátá středa to je. Mělo by tam být třeba rok dopředu na každý měsíc kdy jsou tušená pyva, a označeno třeba otazníkem a v popisu nějak vyznačeno že to ještě není jistý. Jako title by asi stačilo "Pražské Pyvo?" místo "Pražské Pyvo".

**Comment by encukou** [comment]
Ty jo, `ics` to neumí :(
https://github.com/C4ptainCrunch/ics.py/issues/14
