### ISSUE TITLE
Roští: Problém s doménou

### ISSUE THREAD

**Issue by honzajavorek** [pyvec/pyvo.cz#53]
V adminovi vidím tohle:

<img width="880" alt="image" src="https://cloud.githubusercontent.com/assets/283441/22692747/ae51fa62-ed40-11e6-842d-a5b043955dfc.png">

<img width="866" alt="image" src="https://cloud.githubusercontent.com/assets/283441/22692754/b8acd70c-ed40-11e6-81e4-8ea6810fb007.png">

To je bug nebo feature? K pyvo.cz doméně mám přístup já, tak bych to měl asi nějak spravit 😐

**Comment by encukou** [comment]
Feature to není, je to bug. (Ale týká se to jen *legacy*/*convenience* adres jako `brno.pyvo.cz`, které tehdy s `https` nefungovaly)

**Comment by honzajavorek** [comment]
Co muzu udelat abych to fixnul?

**Comment by encukou** [comment]
Zjistit jaké jsou správné IP adresy. (Ale nemyslím že je to nějak prioritní.)

**Comment by encukou** [comment]
Už to tam nevidím.
