### ISSUE TITLE
Paginace pro stránky srazů

### ISSUE THREAD

**Issue by honzajavorek** [pyvec/pyvo.cz#8]
Přemístěno z [Trella](https://trello.com/c/RwPssogm/30-pyvo-cz).

**Comment by torsava** [comment]
I'm taking this. After consultation with @encukou:

- Pagination will be based on years, first page will contain current year + last year (URL /seriers/year/)
- It will contain a link to display all (URL /series/all)
- Buttons at the bottom of the page will be enclosed in grey boxes

**Comment by encukou** [comment]
Zavřeno v PR https://github.com/pyvec/pyvo.cz/pull/52
