### ISSUE TITLE
Řazení meetupů

### ISSUE THREAD

**Issue by frenzymadness** [pyvec/pyvo.cz#86]
Pokud je naplánován více než jeden meetup dopředu, neřadí se správně a na mapce a v přehledu pod ní se nezobrazuje ten nejbližší. Jako například teď v Ostravě.

Kód, který by to měl zařídit tam ovšem je, takže tam bude nějaky bug. https://github.com/pyvec/pyvo.cz/blob/master/pyvocz/views.py#L95

![image](https://user-images.githubusercontent.com/5688939/36960666-5151ae66-2048-11e8-8187-418db8a1d402.png)

**Comment by encukou** [comment]
Stejný problém je na stránce města: https://pyvo.cz/ostrava-pyvo/ ukazuje na prvním místě sraz, který je nejdál v budoucnosti.
