### ISSUE TITLE
Chybí Honzovy malůvky

### ISSUE THREAD

**Issue by honzajavorek** [pyvec/pyvo.cz#9]
Přemístěno z Trella, z [téhle](https://trello.com/c/RwPssogm/30-pyvo-cz) a [téhle](https://trello.com/c/IKJn0tKu/47-udelat-ilustrace-pro-nove-pyvo-cz) kartičky. Closes https://github.com/pyvec/resources/issues/2.

**Comment by encukou** [comment]
Closed via 13928e0
