### ISSUE TITLE
Podpora více různých akcí v jeden den

### ISSUE THREAD

**Issue by oskar456** [pyvec/pyvo.cz#98]
Liberecké Pyvo by se rádo konalo ve stejné termíny jako Brněnské nebo Ostravské Pyvo, ale nemůže, protože web umí v jeden den jen jedno Pyvo.

**Comment by messa** [comment]
Co se tedy stane, když je víc Pyv v jednom dni? :)

**Comment by oskar456** [comment]
Kupodivu to nevybouchne, náhodně se vybere jedna z akcí – zřejmě podle pořadí v pyvo-data repozitáři a ta se zobrazí v kalendáři.

![pyvo-dve-akce](https://user-images.githubusercontent.com/816717/44218710-8e488700-a17a-11e8-9fb0-287fb38410a2.png)

Čili nejspíš stačí nějak vymyslet renderování kalendářového dne pro případ, že v něm jsou dvě akce.
